use_frameworks!

platform :ios, '10.0'

#flutter_application_path = '../flutter_module'
#load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'swift_blp_Example' do
#  pod 'swift_blp', :path => '../'
#  install_all_flutter_pods(flutter_application_path)
  pod 'Alamofire', '4.9.1'
  pod 'Moya', '13.0.1'
  pod 'SwiftyJSON', '5.0.1'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'HandyJSON' #4.1.1 (5.0.2)
  pod 'ZFPlayer', '~> 4.1.4'
  pod 'ZFPlayer/ControlView'
  pod 'ZFPlayer/AVPlayer'
  pod 'EZLoadingActivity'
  pod 'SVProgressHUD'
  pod 'lottie-ios'

  target 'swift_blp_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'RxBlocking', '6.6.0'
#    pod 'RxTest', '6.6.0'
  end
end

#post_install do |installer|
#  flutter_post_install(installer) if defined?(flutter_post_install)
#end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['ENABLE_BITCODE'] = 'NO'
#        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#    end
#  end
#end
