use_frameworks!

platform :ios, '10.0'

target 'swift_blp_Example' do
  pod 'swift_blp', :path => '../'

  target 'swift_blp_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
